# Generated by Django 3.1.5 on 2021-07-08 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210708_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='watchlist',
            new_name='watched',
        ),
    ]
