# Generated by Django 3.1.5 on 2021-07-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210712_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='auction/images/default.jpg', upload_to='auction/images/'),
        ),
    ]
